x<- read.table("household_power_consumption.txt",sep =";",header=TRUE,na.strings = "?",colClasses=c(rep("character",2),rep("numeric",7)))
x$date<-strptime(x$Date,"%d/%m/%Y")
xSubset<-subset(x,date=="2007-02-02"|date=="2007-02-01")
xSubset$date_time <-strptime(paste(xSubset$Date,xSubset$Time),"%d/%m/%Y %H:%M:%S")
png(file="plot2.png", bg="transparent",width = 480, height = 480)
plot(xSubset$date_time,xSubset$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)",main="")
dev.off()
