x<- read.table("household_power_consumption.txt",sep =";",header=TRUE,na.strings = "?",colClasses=c(rep("character",2),rep("numeric",7)))
x$date<-strptime(x$Date,"%d/%m/%Y")
xSubset<-subset(x,date=="2007-02-02"|date=="2007-02-01")
xSubset$date_time <-strptime(paste(xSubset$Date,xSubset$Time),"%d/%m/%Y %H:%M:%S")
png(file="plot3.png", bg="transparent",width = 480, height = 480)
plot(xSubset$date_time,xSubset$Sub_metering_1,type="n",xlab="",ylab = "Energy sub metering")
points(xSubset$date_time,xSubset$Sub_metering_1,type="l",col="black")
points(xSubset$date_time,xSubset$Sub_metering_2,type="l",col="red")
points(xSubset$date_time,xSubset$Sub_metering_3,type="l",col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col = c("black","red","blue"))
dev.off()
